//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wystawiacz_faktur.RepositoryEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class praktyki2026Entities : DbContext
    {
        public praktyki2026Entities()
            : base("name=praktyki2026Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<faktura_poz> faktura_poz { get; set; }
        public virtual DbSet<kontrahent> kontrahent { get; set; }
    }
}
