//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wystawiacz_faktur.RepositoryEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class faktura_poz
    {
        public int id_faktura_poz { get; set; }
        public string nazwa { get; set; }
        public Nullable<decimal> cena_brutto { get; set; }
        public Nullable<decimal> cena_netto { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string Jedn_miary { get; set; }
        public Nullable<decimal> wartosc_vat { get; set; }
        public Nullable<int> ilosc { get; set; }
    }
}
