//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wystawiacz_faktur.RepositoryEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontrahent
    {
        public int id_nabywca { get; set; }
        public string nazwa { get; set; }
        public string NIP { get; set; }
        public string adres { get; set; }
        public string numer_konta { get; set; }
        public string kod_pocztowy { get; set; }
        public string miasto { get; set; }
        public string typ { get; set; }
    }
}
